global:
  scrape_interval:     1s
  evaluation_interval: 1s
scrape_configs:
  - job_name: 'prometheus'
    static_configs:  # TODO ip地址自己填我有相同的端口，因为是有两台机器，你们可以干掉相同的端口
      - targets: ['127.0.0.1:9090']
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['127.0.0.1:8899']
  - job_name: 'node'
    static_configs:
      - targets: ['127.0.0.1:9100']
  - job_name: 'austin'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['127.0.0.1:8888']